version: "3"
services:
  node-app:
    build: .
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./.env
  
  mongo:
    image: mongo
    # environment:
    env_file:
      - ./.env