version: '3'
services:
  node-app:
    build: # Overriding the base docker-compose.yml
      context: . # path to dockerfile
      args:
        - NODE_ENV=development
    volumes:
      # Bind mount for dev environment.
      - ./:/app 
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev